### ISSUE TITLE
Add new districts

### ISSUE THREAD

**Issue by vamsisudhakaran** [kishaningithub/cowin-vaccine-alerter#1]
Add the following districts to reach much more people in chennai
Chengalpet
Kanchipuram

new cities
Bengaluru

**Comment by kishaningithub** [comment]
@vamsisudhakaran Currently bangalore is comprised of 2 districts "Bangalore Rural" and "Bangalore Urban" do you want alerts for both of these places to appear in the same chat/telegram group?

**Comment by kishaningithub** [comment]
@vamsisudhakaran Have completed addition of chengalpet and kanchipuram. You can find the telegram links for these locations in the hompage - https://kishaningithub.github.io/cowin-vaccine-alerter/

**Comment by kishaningithub** [comment]
Have added the following districts in karnataka

- Karnataka / Bangalore Rural
- Karnataka / Bangalore Urban
- Karnataka / BBMP

Latest list
 https://kishaningithub.github.io/cowin-vaccine-alerter/
